wandb_version: 1

problem:
  desc: null
  value: tsp
graph_size:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 100
epoch_size:
  desc: null
  value: 10000
val_size:
  desc: null
  value: 10000
val_dataset:
  desc: null
  value: null
model:
  desc: null
  value: attention
embedding_dim:
  desc: null
  value: 128
hidden_dim:
  desc: null
  value: 128
n_encode_layers:
  desc: null
  value: 3
tanh_clipping:
  desc: null
  value: 10.0
normalization:
  desc: null
  value: batch
method:
  desc: null
  value: pg
lr_model:
  desc: null
  value: 0.0001
lr_critic:
  desc: null
  value: 0.0001
lr_decay:
  desc: null
  value: 1.0
eval_only:
  desc: null
  value: false
n_epochs:
  desc: null
  value: 100
seed:
  desc: null
  value: 1234
max_grad_norm:
  desc: null
  value: 1.0
no_cuda:
  desc: null
  value: false
exp_beta:
  desc: null
  value: 0.8
baseline:
  desc: null
  value: null
bl_alpha:
  desc: null
  value: 0.05
bl_warmup_epochs:
  desc: null
  value: 0
eval_batch_size:
  desc: null
  value: 100
checkpoint_encoder:
  desc: null
  value: false
shrink_size:
  desc: null
  value: null
data_distribution:
  desc: null
  value: null
log_step:
  desc: null
  value: 50
log_dir:
  desc: null
  value: logs
run_name:
  desc: null
  value: run_pg_1234_20240207T205902
output_dir:
  desc: null
  value: outputs
epoch_start:
  desc: null
  value: 0
checkpoint_epochs:
  desc: null
  value: 1
load_path:
  desc: null
  value: null
resume:
  desc: null
  value: null
no_tensorboard:
  desc: null
  value: false
no_progress_bar:
  desc: null
  value: false
wandb:
  desc: null
  value: online
use_cuda:
  desc: null
  value: true
save_dir:
  desc: null
  value: outputs/tsp_20/run_pg_1234_20240207T205902
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707307143.983577
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
